universal7885: FMRadio: jni: remove unused function
* device/samsung/universal7885/apps/FMRadio/jni/fm_ioctl.cpp:65:12: error: unused function 'fm_radio_get_control' [-Werror,-Wunused-funct
ion]
static int fm_radio_get_control(int fd, unsigned int id, long *val)
           ^
1 error generated.
06:47:41 ninja failed with: exit status 1

* Also, fix wrong native lib name (fmradioioctl_jni -> fmioctl_jni)